---
# tasks file for cjsteel.providers

- name: Ensure for local projects parent directory
  delegate_to: 127.0.0.1
  file:
    path: "{{ providers_projects_parent }}"
    state: directory
    mode: 0700

## default (docker) scenario customizations

- name: Ensure for local projects molecule default (docker) directory
  delegate_to: 127.0.0.1
  file:
    path: "{{ providers_project_directory }}/molecule/default"
    state: directory
    mode: 0700
  when: providers_update_all_files or
        providers_update_docker_all_files

- name: Copy local default (docker) scenario provider file Dockerfile.j2
  delegate_to: 127.0.0.1
  copy:
    src: templates/default/Dockerfile.j2
    dest: "{{ providers_project_directory }}/molecule/default/Dockerfile.j2"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_dockerfile or
        providers_update_docker_all_files or
        providers_update_docker_dockerfile

- name: Template local default (docker) scenario provider file INSTALL.rst
  delegate_to: 127.0.0.1
  template:
    src: templates/default/INSTALL.rst.j2
    dest: "{{ providers_project_directory }}/molecule/default/INSTALL.rst"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_install_rst or
        providers_update_docker_all_files or
        providers_update_docker_install_rst

- name: Template local default (docker) scenario provider file molecule.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/default/molecule.yml.j2
    dest: "{{ providers_project_directory }}/molecule/default/molecule.yml"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_molecule_yml or
        providers_update_docker_all_files or
        providers_update_docker_molecule_yml

- name: Template local default (docker) scenario provider file playbook.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/default/playbook.yml.j2
    dest: "{{ providers_project_directory }}/molecule/default/playbook.yml"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_playbook_yml or
        providers_update_docker_all_files or
        providers_update_docker_playbook_yml

- name: Template local default (docker) scenario provider file playbook2.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/default/playbook2.yml.j2
    dest: "{{ providers_project_directory }}/molecule/default/playbook2.yml"
    mode: 0700
    force: "{{ providers_force }}"
    backup: "{{ providers_backup_playbook2 }}"
  when: providers_update_all_files or
        providers_update_all_playbook2_yml or
        providers_update_docker_all_files or
        providers_update_docker_playbook2_yml

## lxd scenario customizations

- name: Ensure for local projects molecule lxd scenario directory
  delegate_to: 127.0.0.1
  file:
    path: "{{ providers_project_directory }}/molecule/lxd"
    state: directory
    mode: 0700
  when: providers_update_all_files or
        providers_update_lxd_all_files

- name: Template local lxd scenario provider file INSTALL.rst
  delegate_to: 127.0.0.1
  template:
    src: templates/lxd/INSTALL.rst.j2
    dest: "{{ providers_project_directory }}/molecule/lxd/INSTALL.rst"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_install_rst or
        providers_update_lxd_all_files or
        providers_update_lxd_install_rst

- name: Template local lxd scenario provider file molecule.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/lxd/molecule.yml.j2
    dest: "{{ providers_project_directory }}/molecule/lxd/molecule.yml"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_molecule_yml or
        providers_update_lxd_all_files or
        providers_update_lxd_molecule_yml

- name: Template local lxd scenario provider file playbook.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/lxd/playbook.yml.j2
    dest: "{{ providers_project_directory }}/molecule/lxd/playbook.yml"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_playbook_yml or
        providers_update_lxd_all_files or
        providers_update_lxd_playbook_yml

- name: Template local lxd scenario provider file playbook2.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/lxd/playbook2.yml.j2
    dest: "{{ providers_project_directory }}/molecule/lxd/playbook2.yml"
    mode: 0700
    force: "{{ providers_force }}"
    backup: "{{ providers_backup_playbook2 }}"
  when: providers_update_all_files or
        providers_update_all_playbook2_yml or
        providers_update_lxd_all_files or
        providers_update_lxd_playbook2_yml

## vagrant scenario customizations

- name: Ensure for local projects molecule vagrant scenario directory
  delegate_to: 127.0.0.1
  file:
    path: "{{ providers_project_directory }}/molecule/vagrant"
    state: directory
    mode: 0700
  when: providers_update_all_files or
        providers_update_vagrant_all_files

- name: Template local vagrant scenario provider file INSTALL.rst
  delegate_to: 127.0.0.1
  template:
    src: templates/vagrant/INSTALL.rst.j2
    dest: "{{ providers_project_directory }}/molecule/vagrant/INSTALL.rst"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_install_rst or
        providers_update_vagrant_all_files or
        providers_update_vagrant_install_rst

- name: Template local vagrant scenario provider file molecule.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/vagrant/molecule.yml.j2
    dest: "{{ providers_project_directory }}/molecule/vagrant/molecule.yml"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_molecule_yml or
        providers_update_vagrant_all_files or
        providers_update_vagrant_molecule_yml

- name: Template local vagrant scenario provider file playbook.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/vagrant/playbook.yml.j2
    dest: "{{ providers_project_directory }}/molecule/vagrant/playbook.yml"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_playbook_yml or
        providers_update_vagrant_all_files or
        providers_update_vagrant_playbook_yml

- name: Template local vagrant scenario provider file playbook2.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/vagrant/playbook2.yml.j2
    dest: "{{ providers_project_directory }}/molecule/vagrant/playbook2.yml"
    mode: 0700
    force: "{{ providers_force }}"
    backup: "{{ providers_backup_playbook2 }}"
  when: providers_update_all_files or
        providers_update_all_playbook2_yml or
        providers_update_vagrant_all_files or
        providers_update_vagrant_playbook2_yml

- name: Template local vagrant scenario provider file prepare.yml
  delegate_to: 127.0.0.1
  template:
    src: templates/vagrant/prepare.yml.j2
    dest: "{{ providers_project_directory }}/molecule/vagrant/prepare.yml"
    mode: 0700
    force: "{{ providers_force }}"
  when: providers_update_all_files or
        providers_update_all_prepare_yml or
        providers_update_vagrant_all_files or
        providers_update_vagrant_prepare_yml
