---
- name: Converge
  hosts: all
  vars:
    - virtualbox_deployment_users_home: /home/vagrant
    - virtualbox_testing_provider: vagrant
  roles:
    - role: '{{ provider_role_owner }}.{{ provider_role_short_name }}'
